- id: "automation_tradfri_bedroom_long_press"
  alias: "Tradfri - Bedroom Long Press"
  description: ""
  trigger:
    - device_id: 2ff778a4db317904b52046b29aedb380
      domain: zha
      platform: device
      type: remote_button_long_press
      subtype: dim_up
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.nightmode_run
              state: "off"
          sequence:
            - service: script.toggle_all_lights
        - conditions:
            - condition: state
              entity_id: input_boolean.nightmode_run
              state: "on"
          sequence:
            - service: script.toggle_nightlight_mode
      default: []
  mode: single
- id: "1632332603081"
  alias: Tradfri - Kitchen Click
  description: ""
  trigger:
    - device_id: 1b1b862e348fead81130779105f482c2
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.kitchen_1
              state: "on"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.kitchen_lights
      default:
        - service: script.turn_on_kitchen_light
  mode: single
- id: "1632333367870"
  alias: Tradfri - Lamp Click
  description: ""
  trigger:
    - device_id: adb0a9ccf4dc25c54c0f1e663db21a16
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.lamp
              state: "on"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.lamp
      default:
        - service: script.turn_on_lamp
  mode: single
- id: "1632333756268"
  alias: Tradfri - Lamp Long Press
  description: ""
  trigger:
    - device_id: adb0a9ccf4dc25c54c0f1e663db21a16
      domain: zha
      platform: device
      type: remote_button_long_press
      subtype: dim_up
  condition: []
  action:
    - service: tts.cloud_say
      data:
        entity_id: media_player.living_room_speaker
        message: Stub script for the long press activated, James todo
  mode: single
- id: "1632334441089"
  alias: Tradfri - Bedroom Click
  description: ""
  trigger:
    - device_id: 2ff778a4db317904b52046b29aedb380
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: turn_on
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.hue_lamp
              state: "on"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.hue_lamp
      default:
        - service: script.turn_on_hue_light
  mode: single
- id: "1632343890979"
  alias: Tradfri Controller - LeftAndRight
  description: ""
  trigger:
    - device_id: 50ab492764ca791ff169d9a0c5c53c87
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: left
      id: "left"
    - device_id: 50ab492764ca791ff169d9a0c5c53c87
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: right
      id: "right"
    - device_id: 50ab492764ca791ff169d9a0c5c53c87
      domain: zha
      platform: device
      type: remote_button_long_press
      subtype: left
      id: "long_left"
    - device_id: 50ab492764ca791ff169d9a0c5c53c87
      domain: zha
      platform: device
      type: remote_button_long_press
      subtype: right
      id: "long_right"
  condition: []
  action:
    - choose:
        - conditions:
            - condition: or
              conditions:
                - condition: trigger
                  id: "long_right"
                - condition: trigger
                  id: "long_left"
          sequence:
            - service: tts.cloud_say
              data:
                entity_id: media_player.living_room_speaker
                message: Selected light number {{states.input_number.tradfri_controller_selected_light.state | int}}
      default:
        - service: input_number.set_value
          target:
            entity_id: input_number.tradfri_controller_selected_light
          data:
            value: >
              {% if trigger.id == "left" %}
                {% if states.input_number.tradfri_controller_selected_light.state | int > 1 %}
                  {{((states.input_number.tradfri_controller_selected_light.state | int ) - 1 ) |float}}
                {% else %}
                  {{1.0 | float}}
                {% endif %}
              {% else %}
                {% if states.input_number.tradfri_controller_selected_light.state | int < 5 %}
                  {{((states.input_number.tradfri_controller_selected_light.state | int ) + 1) |float}}
                {% else %}
                  {{5.0 | float}}
                {% endif %}
              {% endif %}
  mode: queued
  max: 3
- id: "tradfri_controller_center_click"
  alias: Tradfri Controller - Center Click
  description: "Selecting the center power button on the tradfri controller"
  trigger:
    - device_id: 50ab492764ca791ff169d9a0c5c53c87
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: turn_on
      id: "on"
    # - device_id: 50ab492764ca791ff169d9a0c5c53c87
    #   domain: zha
    #   platform: device
    #   type: remote_button_long_press
    #   subtype: turn_on
    #   id: "long"
  condition: []
  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: input_number.tradfri_controller_selected_light
              below: "4"
          sequence:
            - service: light.toggle
              target:
                entity_id: >
                  {% if is_state("input_number.tradfri_controller_selected_light", "1.0") %}
                    light.lamp
                  {% elif is_state("input_number.tradfri_controller_selected_light", "2.0") %}
                    light.kitchen_lights
                  {% elif is_state("input_number.tradfri_controller_selected_light", "3.0") %}
                    light.hue_lamp
                  {% else %}
                    light.lamp
                  {% endif %}
        - conditions:
            - condition: numeric_state
              entity_id: input_number.tradfri_controller_selected_light
              above: "3"
              below: "5"
          sequence:
            - service: switch.toggle
              target:
                entity_id: switch.68075101840d8e9e9560
        - conditions:
            - condition: numeric_state
              entity_id: input_number.tradfri_controller_selected_light
              above: "4"
              below: "6"
          sequence:
            - service: switch.toggle
              target:
                entity_id: switch.2080834768c63ae47267
      default:
        - service: tts.cloud_say
          data:
            entity_id: media_player.living_room_speaker
            message: Default called?

    # data:
    # color_temp: 380
    # brightness_pct: 100
    # - service: light.turn_on
    # target:
    #     entity_id:
  mode:
    single

    # - service: light.toggle
    #   target:
    #     entity_id: >
    #       {% if is_state("input_number.tradfri_controller_selected_light", 1) %}
    #         light.lamp
    #       {% elif is_state("input_number.tradfri_controller_selected_light", 2) %}
    #         light.kitchen_lights
    #       {% elif is_state("input_number.tradfri_controller_selected_light", 3) %}
    #         light.hue_lamp
    #       {% else %}
    #         light.lamp
    #       {% endif %}
    # data:
    # color_temp: 380
    # brightness_pct: 100
    # - service: light.turn_on
    # target:
    #     entity_id:
